<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
	<!--Uncomment the following line to .net runtimes in the output folder-->
	<!--<RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <UseAppHost>true</UseAppHost>-->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ImagesAndDocuments\ICOFiles\app_icon.ico</ApplicationIcon>
    <DefaultItemExcludes>$(DefaultItemExcludes);LocalOutput\**</DefaultItemExcludes>
    <LocalBuildOutputDirectory>$(MSBuildProjectDirectory)\LocalOutput\Build\</LocalBuildOutputDirectory>
    <Company>DIPSOFT</Company>
    <Description>A file synchronizer software</Description>
    <Copyright>Dipanjan Banik</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="ImagesAndDocuments\ICOFiles\app_icon.ico" />
    <Resource Include="ImagesAndDocuments\ICOFiles\flip_source_dest.ico" />
    <Resource Include=".github\workflows\windows-build.yml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ResourceBundles.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourceBundles.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="ResourceBundles.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceBundles.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="CopyBuildOutputToLocalOutput" AfterTargets="Build" Condition="'$(DesignTimeBuild)' != 'true'">
    <MakeDir Directories="$(LocalBuildOutputDirectory)" />
    <ItemGroup>
      <PreviousLocalBuildOutputFiles Include="$(LocalBuildOutputDirectory)**\*" />
      <PreviousLocalBuildOutputDirectories Include="$([System.IO.Directory]::GetDirectories('$(LocalBuildOutputDirectory)'))" />
      <LocalBuildOutputFiles Include="$(TargetDir)**\*" />
    </ItemGroup>
    <Delete Files="@(PreviousLocalBuildOutputFiles)" />
    <RemoveDir Directories="@(PreviousLocalBuildOutputDirectories)" />
    <Copy SourceFiles="@(LocalBuildOutputFiles)" DestinationFiles="@(LocalBuildOutputFiles->'$(LocalBuildOutputDirectory)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="CleanLocalBuildOutput" AfterTargets="Clean" Condition="'$(DesignTimeBuild)' != 'true'">
    <Exec Command="attrib -R &quot;$(LocalBuildOutputDirectory)*&quot; /S /D" Condition="'$(OS)' == 'Windows_NT' and Exists('$(LocalBuildOutputDirectory)')" />
    <Exec Command="attrib -R &quot;$(LocalBuildOutputDirectory).&quot;" Condition="'$(OS)' == 'Windows_NT' and Exists('$(LocalBuildOutputDirectory)')" />
    <RemoveDir Directories="$(LocalBuildOutputDirectory)" Condition="Exists('$(LocalBuildOutputDirectory)')" />
  </Target>

</Project>
